flowchart LR
    A[Browser] -->|https,1.2.3.4| B[NLB]
    B --> |https,1.2.3.4|C(NBL Service)
    C --> |https,1.2.3.4|D(HTTP Proxy Pod)
    D --> |http,1.2.3.4|P{NetworkPolicy: <br />Allow 1.2.3.4}
    P -->|✅ http|E(App Pod)
    P --> |❌|F[Drop]
